import = [
  "~/.config/alacritty/catppuccin-frappe.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14.0
normal.family = "Fira Code"
bold.family = "Fira Code"
italic.family = "Fira Code"
bold_italic.family = "Fira Code"
